import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Hero from "./components/Hero";
// import Services from "./components/Services";
// import Chefs from "./components/Chefs";
// import Brands from "./components/Brands";
// import Process from "./components/Process";
// import Portfolio from "./components/Portfolio";
// import Contact from "./components/Contact";
// import Footer from "./components/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
        <Header />
        <main>
          <Hero />
          {/* <Services />
          <Chefs />
          <Brands />
          <Process />
          <Portfolio />
          <Contact /> */}
        </main>
        {/* <Footer /> */}

      </body>
    </html>
  );
}
